### PR TITLE
Added new metrics and updated gobgp version used.

### PR DESCRIPTION
**Pull request by piotrsuchy**
Updated gobgp version used from v3.12.0 to v3.27.0 + commits until 7d2d020bd226, as that version of gobgp has a useful bugfix. 
Also added new metrics:
- bgpPeerAfiSafiStateAccepted, for count of accepted prefixes
- bgpPeerAfiSafiStateAdvertised, for count of advertised prefixes
- bgpPeerAfiSafiStateReceived, for count of received prefixes

Our company's fork of gobgp_exporter got a bit ahead of the upstream so we would love to get this merged, and continue working on the upstream repo instead of our fork. Please give us feedback or let us know if merging is possible :)

### CODE REVIEW

**Comment by greenpau** [comment]
@mrueg , i hope all is well! Do you still use the exporter? I am hoping to find someone to review the PR, because the last time I touched GoBGP was probably 5 years ago.

**Comment by mrueg** [comment]
👋 @greenpau 

gobgp now has prometheus support built in https://github.com/osrg/gobgp/blob/ad7dc34e102097cf338cea26b73de3f05d6a8029/internal/pkg/metrics/metrics.go 

might be worth adding those there.

**Comment by greenpau** [comment]
> gobgp now has prometheus support built in

@mrueg , thank you for quick reply! Do you think it is worth maintaining this exporter?

**Comment by greenpau** [comment]
@piotrsuchy , does Akamai want to maintain this exporter? If yes, I am open to discuss.

**Comment by mrueg** [comment]
> > gobgp now has prometheus support built in
> 
> @mrueg , thank you for quick reply! Do you think it is worth maintaining this exporter?

Ideally, missing metrics would be included in gobgp's upstream and this one wouldn't be needed anymore.

**Comment by greenpau** [comment]
@piotrsuchy , please see @mrueg , why don’t you use the exporter included with GoBGP?

**Comment by piotrsuchy** [comment]
Hello, thanks for the involvement! We are using gobgp_exporter mostly for legacy reasons, as we were using gobgp exporter before there were standalone metrics for gobgp. If that's something you agree on we would be willing to maintain the exporter. However using gobgp directly might be the better approach - I will talk to the rest of the people involved and will come back to you with a response.

**Comment by piotrsuchy** [comment]
Hello again, after some further talks with the rest of the team we decided to try to upstream our changes with additional metrics to gobgp directly. In the meantime we will still probably work on the fork of gobgp_exporter for our 'more internal' and less general stuff. Thanks for the feedback, I'm closing this PR.

**Pull request closed without merging**
