### PR TITLE
Adding description label to peer-specific metrics

### PR DESCRIPTION
**Pull request by fach**
This PR adds the gobgp configured peer description as a label to peer-specific metrics. This allows for upstream relabeling in prometheus based on structured peer descriptions.

### CODE REVIEW

**Comment by greenpau** [comment]
@fach , thank you for the PR! Unfortunately, by adding the description to each metric, the cardinality changes dramatically. I suggest you consider the followin.

Please add `gobgp_router_info` metrics with various labels important for you, e.g. description. The value of `gobgp_router_info` should always be `1`.

Next, you can use the `gobgp_router_info` metric with any other metric to get the response that would contain `description`.

Here is the hint.

```
probe_host * on(instance,job) group_left( ipv4_address, ipv6_address, mac_address, service) probe_info
```

**Comment by fach** [comment]
Thanks for the feedback. Should this be called `gobgp_peer_info` as opposed to `gobgp_router_info`?

**Comment by greenpau** [comment]
@fach , I think it make sense to having `_info` at `gobgp_router_` and `gobgp_peer_` levels.

**Comment by greenpau** [comment]
>  I think it make sense to having _info at gobgp_router_ and gobgp_peer_ levels.

@fach , having description on all metrics does not make sense. There is probably another way for you to get description (e.g. joining with the `info`.

**Pull request closed without merging**
